# Generated by Django 4.2 on 2023-04-05 12:32
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("Soft", "Soft"), ("Hard", "Hard")],
                        default="Hard",
                        max_length=4,
                    ),
                ),
                ("inventory", models.PositiveIntegerField()),
                ("daily_fee", models.DecimalField(
                    decimal_places=2,
                    max_digits=9,
                    validators=(MinValueValidator(limit_value=0.01),),)),

            ],
        ),
    ]
